---
- name: "Wait for SSH coming up (timeout: {{ wait_timeout | default(120)}}s)"
  wait_for_connection:
    timeout: "{{ wait_timeout | default(120)}}"

- meta: clear_facts

- name: Gather facts for {{ server_hostname }}
  setup:
