---

- name: "Force disabling unattended upgrades config for {{ ansible_os_family }}"
  block:

    - name: "Disable timer for unattended upgrades"
      ansible.builtin.systemd_service:
        daemon_reload: true
        name: dnf-automatic.timer
        enabled: no
        state: stopped

  when: ansible_os_family == 'RedHat' and ansible_distribution_version.split('.')[0] | int > 8

#- name: "Force disabling unattended upgrades config for {{ ansible_os_family }}"
#  block:
#
#  when: ansible_os_family == 'Debian'
