---

- include: activate_unattended_updates.yml
  when:
    - unattended_system_upgrade.enabled | d(False)
    - not unattended_system_upgrade.forcedisable | d(False)

- include: disable_unattended_updates.yml
  when: 
    - unattended_system_upgrade.forcedisable | d(False) or unattended_system_upgrade_forcedisable | d(False)
