---

- name: "update pkg cache (debian)"
  apt:
    update_cache: true
  when: ansible_facts['os_family'] == "Debian"

- name: "update pkg cache (redhat)"
  dnf:
    update_cache: true
  when: ansible_facts['os_family'] == "RedHat"

- name: "update pkg cache (suse)"
  community.general.zypper:
    update_cache: true
  when: ansible_facts['os_family'] == "Suse"

