- name: Format new disk storage
  hosts: "{{ server_hostname }}*"
  gather_facts: False

  tasks:
    - name: Power on if needed
      debug: msg="Please be patient as we wait until the VM is fully booted!"

    - name: Power on {{ server_hostname }}
      include_tasks: vcenter_poweron-vm.yml

    - name: include any system boot tasks
      include_role:
        name: system_boot

    - name: partitioning {{ server_disk_dev }}
      remote_user: "{{ pors_ssh_user }}"
      become: yes
      parted: 
        device: "{{ server_disk_dev }}" 
        number: 1
        flags: [ lvm ]
        label: gpt
        state: present
      when: server_scnd_disk is defined and server_disk_dev is defined 
   
    - name: create new lvm volgroup {{ server_lvm_vg }} with {{ server_disk_dev }}1
      remote_user: "{{ pors_ssh_user }}"
      become: yes
      lvg:
        vg: "{{ server_lvm_vg }}"
        pvs: "{{ server_disk_dev }}1"
      when: server_scnd_disk is defined and server_disk_dev is defined

    - name: create {{ server_lvm_lv }} logical volume in {{ server_lvm_vg }}
      remote_user: "{{ pors_ssh_user }}"
      become: yes
      lvol:
        vg: "{{ server_lvm_vg }}"
        lv: "{{ server_lvm_lv }}"
        size: 100%FREE
      when: server_scnd_disk is defined and server_disk_dev is defined

    - name: format /dev/mapper/{{ server_lvm_vg }}-{{ server_lvm_lv }} with {{ server_disk_fs }}
      remote_user: "{{ pors_ssh_user }}"
      become: yes
      filesystem:
        fstype: "{{ server_disk_fs }}"
        dev: "/dev/mapper/{{ server_lvm_vg }}-{{ server_lvm_lv }}"
      when: server_scnd_disk is defined and server_disk_dev is defined
   
    - name: add {{ server_disk_mountpoint }} to fstab
      remote_user: "{{ pors_ssh_user }}"
      become: yes
      mount:
        src: "/dev/mapper/{{ server_lvm_vg }}-{{ server_lvm_lv }}"
        path: "{{ server_disk_mountpoint }}"
        opts: "{{ server_disk_mountopts }}"
        fstype: "{{ server_disk_fs }}"
        passno: 2
        backup: yes
        state: present
      when: server_scnd_disk is defined and server_disk_dev is defined

    - name: create mountpoint {{ server_disk_mountpoint }} 
      remote_user: "{{ pors_ssh_user }}"
      become: yes
      file:
        path: "{{ server_disk_mountpoint }}"
        mode: '0755'
        state: directory
      when: server_scnd_disk is defined and server_disk_dev is defined
