- name: Add new disk storage
  hosts: "{{ server_hostname }}*"
  gather_facts: False
  connection: local

  tasks:
    - name: Gather disk facts from {{ server_hostname }}
      community.vmware.vmware_vm_info:
        hostname: '{{ vsphere.host[vsphere_var].dest }}'
        username: '{{ vsphere.host[vsphere_var].user }}'
        password: '{{ vsphere.host[vsphere_var].password }}'
        validate_certs: "{{ vsphere.host[vsphere_var].validate_certs }}"
#        datacenter: "{{ vsphere_datacenter }}"
        vm_name: '{{ server_hostname }}'
      register: vgf

    - name: debug out
      debug:
        msg: |
          disk vgf:{{ vgf.virtual_machines }}
      when: debug_on is defined

    - name: Shutdown {{ server_hostname }} if needed
      vmware_guest:
        hostname: '{{ vsphere.host[vsphere_var].dest }}'
        username: '{{ vsphere.host[vsphere_var].user }}'
        password: '{{ vsphere.host[vsphere_var].password }}'
        validate_certs: "{{ vsphere.host[vsphere_var].validate_certs }}"
        name: '{{ server_hostname }}'
        esxi_hostname: "{{ vsphere_esx_host }}"
        state: shutdownguest
      when: item.power_state != 'poweredOff'
      loop: "{{ vgf.virtual_machines }}"

    - name: Rest after shutdown
      command: sleep 1m
      when: item.power_state != 'poweredOff'
      loop: "{{ vgf.virtual_machines }}"

    - name: "Hint: disk no. {{ server_disk_num }} ({{ server_disk_sizegb }} GB) to {{ server_hostname }}"
      debug: msg="You have selected {{ server_disk_type }} - Please be patient as this might take a while and can even timeout on large disks (e.g. > 50 TB). If that happens you have to increase the 'async' value within 'playbooks/vmware/ae_vm_add-new-disk.yml'. Watch the vCenter for the progress."
      when: server_disk_type == "eagerzeroedthick"

    - name: "Add disk no. {{ server_disk_num }} ({{ server_disk_sizegb }} GB) to {{ server_hostname }} (full wipe --> long wait timeout)"
      vmware_guest_disk:
            hostname: '{{ vsphere.host[vsphere_var].dest }}'
            username: '{{ vsphere.host[vsphere_var].user }}'
            password: '{{ vsphere.host[vsphere_var].password }}'
            validate_certs: "{{ vsphere.host[vsphere_var].validate_certs }}"
            datacenter: "{{ vsphere_datacenter }}"
            name: '{{ server_hostname }}'
            folder: "/{{ vsphere_datacenter }}/vm"
            disk: 
            - size_gb: "{{ server_disk_sizegb }}"
              scsi_controller: "{{ server_scsi_controller }}"
              unit_number: "{{ server_disk_num | int + 1 | abs }}"
              datastore: "{{ vsphere_datastore }}"
              type: "{{ server_disk_type }}"
      async: 28800
      poll: 20
      when: server_disk_type == "eagerzeroedthick"
       
    - name: "Add disk no. {{ server_disk_num }} ({{ server_disk_sizegb }} GB) to {{ server_hostname }} (normal provisioning)"
      vmware_guest_disk:
            hostname: '{{ vsphere.host[vsphere_var].dest }}'
            username: '{{ vsphere.host[vsphere_var].user }}'
            password: '{{ vsphere.host[vsphere_var].password }}'
            validate_certs: "{{ vsphere.host[vsphere_var].validate_certs }}"
            datacenter: "{{ vsphere_datacenter }}"
            name: '{{ server_hostname }}'
            folder: "/{{ vsphere_datacenter }}/vm"
            disk: 
            - size_gb: "{{ server_disk_sizegb }}"
              scsi_controller: "{{ server_scsi_controller }}"
              unit_number: "{{ server_disk_num | int + 1 | abs }}"
              datastore: "{{ vsphere_datastore }}"
              type: "{{ server_disk_type }}"
      when: server_disk_type != "eagerzeroedthick"

    - name: start VM (this task will wait for IP)
      include_tasks: vcenter_poweron-vm.yml 
