---
- hosts: '{{ server_hostname }}*'
  remote_user: "{{ pors_ssh_user }}"
  gather_facts: false

  vars:
    ansible_ssh_user: "{{ pors_ssh_user }}"

  tasks:

  - name: "Execute any pre-destroy commands"
    become: yes
    ansible.builtin.shell: "{{ custom_pre_destroy_cmd }}"
    when: custom_pre_destroy_cmd is defined
    delegate_to: "{{ server_hostname }}"

  - name: "Destroying the VM now.."
    become: no
    debug:
      msg: "Please be patient or watch the progress at the vCenter"

  - name: Power off VM
    become: no
    connection: local
    community.vmware.vmware_guest:
        proxy_host: "{{ vsphere.host[vsphere_var].proxy_host | d('') }}"
        proxy_port: "{{ vsphere.host[vsphere_var].proxy_port | d() | int }}"
        hostname: '{{ vsphere.host[vsphere_var].dest }}'
        username: '{{ vsphere.host[vsphere_var].user }}'
        password: '{{ vsphere.host[vsphere_var].password }}'
        validate_certs: "{{ vsphere.host[vsphere_var].validate_certs }}"
        esxi_hostname: "{{ vsphere_esx_host }}"
        datacenter: "{{ vsphere_datacenter }}"
        name: "{{ server_hostname | regex_replace('\\..*','') }}"
        folder: "/{{ vsphere_datacenter }}/vm"
        state: poweredoff

  - name: Destroy VM 
    become: no
    connection: local
    community.vmware.vmware_guest:
        proxy_host: "{{ vsphere.host[vsphere_var].proxy_host | d('') }}"
        proxy_port: "{{ vsphere.host[vsphere_var].proxy_port | d() | int }}"
        hostname: '{{ vsphere.host[vsphere_var].dest }}'
        username: '{{ vsphere.host[vsphere_var].user }}'
        password: '{{ vsphere.host[vsphere_var].password }}'
        validate_certs: "{{ vsphere.host[vsphere_var].validate_certs }}"
        esxi_hostname: "{{ vsphere_esx_host }}"
        datacenter: "{{ vsphere_datacenter }}"
        name: "{{ server_hostname | regex_replace('\\..*','') }}"
        delete_from_inventory: false
        state: absent
