---
- name: Import checks
  import_tasks: service_checks.yml

- name: Stop daemon
  service: name=cribl
           state=stopped

- name: "Stop by binary"
  become: yes
  become_user: "{{ cribl_install_user }}" 
  shell: "{{ logstream_installation.home_path }}/bin/cribl stop"
