---

# check for existence of splunk init file
- stat: path=/etc/init.d/cribl
  register: criblinitfile

- name: show cribl version
  debug: 
    msg: "cribl version is: >{{ logstream_versionnum }}<"
    
# check for existence of init file
- stat: path=/etc/init.d/cribl
  register: initfile

# file attr doesnt work and is available in ansible version >= v2.3 only
- name: Remove protection from init.d script
  shell: chattr -i /etc/init.d/cribl
  when: initfile is defined and initfile.stat.exists

- name: Remove old initd service
  shell: "chattr -i /etc/init.d/cribl; yes | {{ logstream_installation.home_path }}/bin/cribl boot-start disable -m initd"
  when:
    - (initfile is defined and initfile.stat.exists == true)
    - ansible_facts.service_mgr == "systemd"

- name: "Install service ({{ ansible_facts.service_mgr }})"
  shell: "yes | {{ logstream_installation.home_path }}/bin/cribl boot-start enable -m {{ ansible_facts.service_mgr }} -u {{ cribl_install_user }}"
  when: 
    - (initfile is not defined or initfile.stat.exists != true) or logstream_upgrade == True

- name: Reload init.d conf
  systemd:
    daemon_reload: true
  when: ansible_facts.service_mgr == "systemd"

- name: Ensure logstream runs as correct user
  lineinfile:
    path: /etc/init.d/cribl
    backrefs: yes
    regexp: '(^USER=")(.*)(")'
    line: '\1{{ cribl_install_user }}\3'
  when: ansible_facts.service_mgr != "systemd"

- name: Enable init/systemd for cribl
  service:
    name: cribl
    enabled: yes
