---
- name: "Partitioning {{ part_dev_name.stdout }}"
  parted:
    device: "{{ part_dev_name.stdout }}"
    number: 1
    label: gpt
    state: present
  when: server_disk_dev is defined

- name: "Make {{ part_dev_name.stdout }} a swap device"
  shell: "mkswap {{ server_disk_dev }}1"
  when: server_disk_dev is defined

- name: "add {{ part_dev_name.stdout }} to fstab"
  mount:
    src: "{{ part_dev_name.stdout }}1"
    path: none
    opts: "{{ server_disk_mountopts | default('sw')}}"
    fstype: swap
    passno: "0"
    backup: yes
    state: present
  when: server_disk_dev is defined

- name: "Enable the new swap space"
  shell: swapon -a
