---
- name: "partitioning {{ part_dev_name.stdout }}"
  parted: 
    device: "{{ part_dev_name.stdout }}"
    number: 1
    label: gpt
    state: present
  when: server_disk_dev is defined 

- name: "format {{ part_dev_name.stdout }} with {{ server_disk_fs }}"
  filesystem:
    fstype: "{{ server_disk_fs }}"
    dev: "{{ part_dev_name.stdout }}1"
  when: server_disk_dev is defined

- name: "add {{ part_dev_name.stdout }} to fstab"
  mount:
    src: "{{ part_dev_name.stdout }}1"
    path: "{{ server_disk_mountpoint }}"
    opts: "{{ server_disk_mountopts | default('defaults', true)}}"
    fstype: "{{ server_disk_fs }}"
    passno: "0"
    backup: yes
    state: present
  when: server_disk_dev is defined

- name: "create mountpoint {{ server_disk_mountpoint }}"
  file:
    path: "{{ server_disk_mountpoint }}"
    mode: '0755'
    state: directory
  when: server_disk_dev is defined and server_disk_mountpoint != "none"
