---
- name: "Create temp mount {{ server_tmp_mnt }}"
  file:
    path: "{{ server_tmp_mnt }}"
    state: directory

- name: "Mount new disk {{ server_disk_dev }} to temp mount {{ server_tmp_mnt }} (no LVM)"
  mount:
    src: "{{ server_disk_dev }}1"
    path: "{{ server_tmp_mnt }}"
    fstype: "{{ server_disk_fs }}"
    state: mounted
  when: server_lvm_lv is undefined

- name: "Mount new disk {{ server_lvm_vg }}-{{ server_lvm_lv }} to temp mount {{ server_tmp_mnt }} (LVM)"
  mount:
    src: "/dev/mapper/{{ server_lvm_vg }}-{{ server_lvm_lv }}"
    path: "{{ server_tmp_mnt }}"
    fstype: "{{ server_disk_fs }}"
    state: mounted
  when: server_lvm_lv is defined

- name: "Copy content of {{ server_disk_mountpoint }} to {{ server_tmp_mnt }}"
  ansible.builtin.copy:
    remote_src: true
    src: "{{ server_disk_mountpoint }}/"
    dest: "{{ server_tmp_mnt }}"
    mode: preserve

- name: "Unmount and remove temp mount {{ server_tmp_mnt }}"
  mount:
    path: "{{ server_tmp_mnt }}"
    state: absent

- name: "Update fstab -> {{ server_disk_dev }} (no LVM)"
  mount:
    src: "{{ server_disk_dev }}1"
    path: "{{ server_disk_mountpoint }}"
    fstype: "{{ server_disk_fs }}"
    state: mounted
  when: server_lvm_lv is undefined

- name: "Update fstab -> {{ server_lvm_vg }}-{{ server_lvm_lv }} (LVM)"
  mount:
    src: "/dev/mapper/{{ server_lvm_vg }}-{{ server_lvm_lv }}"
    path: "{{ server_disk_mountpoint }}"
    fstype: "{{ server_disk_fs }}"
    state: present
  when: server_lvm_lv is defined

#- fail:
#    msg: DEBUG HERE
