---
- set_fact: datetime="{{lookup('pipe','date \"+%Y/%m/%d %H:%M\"')}}"
  run_once: True

- include_role:
    name: ssh/check

#- include_tasks: "{{ base_install_dir }}/roles/system_base/tasks/check_ssh.yml"

- include_tasks: identify_disk.yml

- include_tasks: format_disk_lvm.yml
  when:
    - format_disk_lvm is defined
    - format_disk != "false"
    - server_disk_fs != "swap"

- include_tasks: format_disk_nolvm.yml
  when:
    - format_disk_lvm is undefined
    - format_disk != "false"
    - server_disk_fs != "swap"

- include_tasks: create_swap_nolvm.yml
  when:
    - server_lvm_lv is undefined
    - format_disk != "false"
    - server_disk_fs == "swap"

- include_tasks: fs_move.yml
  when:
    - server_fs_move is defined
    - server_fs_move == "true"
    - server_disk_fs != "swap"
