---
#####################################################################################################################
# Default Variables
#
# !! WARNING: DO NOT TOUCH ANYTHING HERE !! Otherwise you won't be able to update PORS anymore.
#
# Instead:
# overwrite them in your inventories/group_vars/all/xxx.yml
#####################################################################################################################

###### pors.yml ######

pors_user: pors
pors_group: pors
pors_install_dir: /opt/pors
# support legacy var:
base_install_dir: "{{ pors_install_dir }}"
pors_data_dir: /opt/pors_data
pors_ssh_user: ansible-pors
pors_ssh_key: "~/.ssh/{{ pors_ssh_user }}_ed25519"
pors_temp_dir: /tmp/pors
env_inventory_dir: "{{ pors_data_dir }}/inventories/{{ target_env }}"
custom_data_dir: "{{ pors_data_dir }}/custom"
custom_roles_dir: "{{ custom_data_dir }}/roles"
custom_playbooks_dir: "{{ custom_data_dir }}/playbooks"
git_pors_data_push: no
pors_allow_autoupgrade_requirements: false
system_default_shell: /bin/bash
pors_touch_dir: /var/lib/pors

###### splunk_repository.yml #######

repo_base: /opt/pors_repo
splunk_repository:
    repository_root: "{{ repo_base }}/{{ target_env }}"
    repository_owner: "{{ pors_user }}"
    repository_group: "{{ pors_group }}"

####### git.yml ########

remote_system:
    local_gituser: "{{ pors_ssh_user }}"

tokenauth:
    git_ro_user: "{{ vault_git_ro_user }}"
    git_ro_token: "{{ vault_git_ro_token }}"

use_git_apps_filter: false

####### hooks.yml ########

hook_system_playbook: False
hook_system_tasks: False
hook_post_install_splunk: False

custom:
    system_tasks: False
    post_install_splunk: False

####### group_vars/logstream_all/cribl_configuration.yml ######

cribl_ssh_user: "{{ pors_ssh_user }}"
cribl_install_user: clintsharp
cribl_install_group: clintsharp
cribl_optimize:
    initd: true

####### cribl_packages.yml ########

logstream_packages:
  linux_64_tgz:
    package:
      version: "{{ logstream_globversion }}"
      url: 'https://cdn.cribl.io/dl/{{ logstream_globversion }}/{{ logstream_tgzname }}'

###### deployment.yml ########

deployment:
    dir: apps

###### distsearch.conf.yml ########

splunk_distsearch_conf:
    distributedSearch:
      servers: 
        - "{{ groups.peernode }}"

###### idx_clustering.yml #######

idx_cluster_available_sites: site1
idx_cluster_replicationfactor: 1
idx_cluster_searchfactor: 1
idx_cluster_site_replicationfactor: "origin:1,total:1"
idx_cluster_site_searchfactor: "origin:1,total:1"

###### logstream_installation.yml #######

logstream_root_path: /opt
logstream_ulimit_nofile_softhard: 65536
logstream_ulimit_nproc_soft: 16000
logstream_ulimit_nproc_hard: 16000
logstream_ulimit_fsize_soft: unlimited
logstream_ulimit_fsize_hard: unlimited
logstream_ulimit_data_soft: unlimited
logstream_ulimit_data_hard: unlimited

####### splunk_auth.yml #######

splunk_auth:
  admin_password: "{{ vault_splunk_admin_password }}"
  splunk_secret: "{{ vault_splunk_secret }}"

###### splunk_configuration.yml ########

splunk_conf_path: /opt/splunk/etc/system/local
splunk_install_user: splunk
splunk_install_group: splunk
splunk_install_user_shell: /bin/bash
lm_push_license: True

####### splunk_installation.yml ########

splunk_ulimit_nofile_softhard: 65536
splunk_ulimit_nproc_soft: 16000
splunk_ulimit_nproc_hard: 16000
splunk_ulimit_fsize_soft: unlimited
splunk_ulimit_fsize_hard: unlimited
splunk_ulimit_data_soft: unlimited
splunk_ulimit_data_hard: unlimited

####### system_base.yml ########

shared_service_account_as_root: False
test_shared_service_account: False
system_enable_sysprep: True

ntp_enabled: true
ntp_timezone: Europe/Berlin
ntp_manage_config: true
ntp_servers:
    - 0.de.pool.ntp.org iburst
    - 1.de.pool.ntp.org iburst
# NTP server area configuration (leave empty for 'Worldwide').
# See: http://support.ntp.org/bin/view/Servers/NTPPoolServers
ntp_area: ''

ntp_restrict:
  - "127.0.0.1"
  - "::1"

# when true the file /opt/pors_repo/common/sudo/splunk-admin must exist
# which then gets copied into sudoers.d
install_splunk_sudoperms: true

####### system_journald.yml #######

systemd_journal_storage: persistent
systemd_journal_compress: "yes"
systemd_journal_system_max_use: 1G
systemd_journal_system_max_file_size: 200M
systemd_journal_restart_state: restarted

####### proxmox defaults #######

proxmox_target_server_address: 'dhcp'

####### splunk download defaults #######

splunk_packages:

  linux_64_tgz:
    splunk:
      version: "{{ globversion }}"
      url: 'https://download.splunk.com/products/splunk/releases/{{ globversion }}/linux/{{ tgzname }}'

    splunkforwarder:
      version: "{{ globversion }}"
      url: 'https://download.splunk.com/products/universalforwarder/releases/{{ globversion }}/linux/{{ tgzname }}'

####### yum / elrepo defaults #######

system_yum:
  elrepo:
    enabled: False
    # !!!! ensure the following are in quotes - otherwise 'when' condition checks will fail (they expect strings) !!!!
    
    # enable (yes) or disable (no) this repo
    main: "no"
    kernel:
        # enable (yes) or disable (no) this repo
        setup: "no"
        # the kernel package name to install
        name: "kernel-lt"
        # RHEL/CentOS: use grub to set kernel on next boot (0 or any other id number)
        setboot: "0"
        # generate a grub config based on the above
        gengrub: True
    # enable (yes) or disable (no) this repo
    extras: "no"
