---

- name: Install the splunk helper
  hosts: "*:!pors_server"
  remote_user: "{{ pors_ssh_user }}"
  become: yes
  become_user: root
  #no_log: True 
  gather_facts: False

  tasks:
    - include_role:
        name: shelper
      when: shelper_installation.enabled | d(False)
