---
#####################################################################################################################
# Init shcluster
#####################################################################################################################

- name: Run init shcluster-config
  command: "{{ splunk_installation.splunk_home_path }}/bin/splunk init shcluster-config -mgmt_uri https://{{ inventory_hostname }}:8089 -replication_port 9888 -auth 'admin:{{ splunk_auth.admin_password }}'"
  when: splunk_server_conf.shclustering.id is defined
