---

- include: restart_shcmember.yml

- include: state.yml

- include: bootstrap.yml
  when:
    - get_shc_state.rc == 0
    - captain_elected.rc != 0

- include_role:
    name: common_tasks 
    tasks_from: monitoring.yml

- include: restart_shcmember.yml
  when: captain_elected.rc != 0
