---

- include: restart_shcmember.yml

- include: state.yml

- include: bootstrap.yml
  when:
    - not get_shc_state.failed
    - captain_elected.rc != 0

- include_role:
    name: common_tasks 
    tasks_from: monitoring.yml
  when: splunk_installation.deploy_mc_key

- include: restart_shcmember.yml
  when: captain_elected.rc != 0
