---

- name: Configure app files (local/*.conf)
  copy: src="{{ item }}"
        dest="{{ splunk_installation.splunk_home_path }}/etc/apps/{{ app_name }}/local/"
  when: vars[app_variable].apps is defined
  with_fileglob: apps/local/*.conf

- name: Configure deployment-app files (local/*.conf)
  copy: src="{{ item }}"
        dest="{{ splunk_installation.splunk_home_path }}/etc/deployment-apps/{{ app_name }}/local/"
  when: vars[app_variable].deployment_apps is defined
  with_fileglob: deployment-apps/local/*.conf

- name: Configure shcluster/apps files (local/*.conf)
  copy: src="{{ item }}"
        dest="{{ splunk_installation.splunk_home_path }}/etc/shcluster/apps/{{ app_name }}/local/"
  when: vars[app_variable].shcluster_apps is defined
  with_fileglob: shcluster/apps/local/*.conf

- name: Configure master-apps files (local/*.conf)
  copy: src="{{ item }}"
        dest="{{ splunk_installation.splunk_home_path }}/etc/master-apps/{{ app_name }}/local/"
  when: vars[app_variable].master_apps is defined
  with_fileglob: master-apps/local/*.conf

- name: Configure manager-apps files (local/*.conf)
  copy: src="{{ item }}"
        dest="{{ splunk_installation.splunk_home_path }}/etc/manager-apps/{{ app_name }}/local/"
  when: vars[app_variable].manager_apps is defined
  with_fileglob: manager-apps/local/*.conf

- name: Configure app permission file (metadata/local.meta)
  copy: src="{{ item }}"
        dest="{{ splunk_installation.splunk_home_path }}/etc/apps/{{ app_name }}/metadata/"
  when: vars[app_variable].apps is defined
  with_fileglob: apps/metadata/local.meta

- name: Configure deployment-app permission file (metadata/local.meta)
  copy: src="{{ item }}"
        dest="{{ splunk_installation.splunk_home_path }}/etc/deployment-apps/{{ app_name }}/metadata/"
  when: vars[app_variable].deployment_apps is defined
  with_fileglob: deployment-apps/metadata/local.meta

- name: Configure shcluster/apps permission file (metadata/local.meta)
  copy: src="{{ item }}"
        dest="{{ splunk_installation.splunk_home_path }}/etc/shcluster/apps/{{ app_name }}/metadata/"
  when: vars[app_variable].shcluster_apps is defined
  with_fileglob: shcluster/apps/metadata/local.meta

- name: Configure master-apps permission file (metadata/local.meta)
  copy: src="{{ item }}"
        dest="{{ splunk_installation.splunk_home_path }}/etc/master-apps/{{ app_name }}/metadata/"
  when: vars[app_variable].master_apps is defined
  with_fileglob: master-apps/metadata/local.meta

- name: Configure manager-apps permission file (metadata/local.meta)
  copy: src="{{ item }}"
        dest="{{ splunk_installation.splunk_home_path }}/etc/manager-apps/{{ app_name }}/metadata/"
  when: vars[app_variable].manager_apps is defined
  with_fileglob: manager-apps/metadata/local.meta
