---

- name: "Create private SSH key for user: {{ user_name }}"
  connection: local
  community.crypto.openssh_keypair:
    path: "~/.ssh/{{ user_name }}_ed25519"
    type: ed25519

# we do not use community.general.ssh_config as it expects a valid hostname
# aaaaand when using the wildcard "*" it will not work properly and re-add
# on each run
- name: "Ensure new key is set in ssh config"
  connection: local
  become: no
  lineinfile:
    path: "~/.ssh/config"
    owner: "{{ pors_user }}"
    mode: 0600
    regex: "^[iI]dentity[fF]ile\\s+{{ pors_ssh_key }}"
    line: "IdentityFile ~/.ssh/{{ user_name }}_ed25519"
    create: yes
    insertbefore: BOF
    state: present
  when: add_local_ssh_config
