---

- block:

    - include: validation.yml
      when: not initial_setup
    - include: create_ssh_key.yml
      when: not var_validation_only

  become: no
  run_once: true
  delegate_to: localhost
