---
- name: "Check power state of VM"
  community.general.proxmox_kvm:
        proxmox_default_behavior: compatibility
        node: "{{ proxmox.node[px_var].name }}"
        api_user: "{{ proxmox.node[px_var].api_user }}"
        api_token_id: "{{ proxmox.node[px_var].api_token_id }}"
        api_token_secret: "{{ proxmox.node[px_var].api_token_secret }}"
        api_host: "{{ proxmox.node[px_var].api_host }}"
        name: "{{ item }}"
        state: current
  register: pwstate
  run_once: True
  loop: "{{ server_hostname }}"

- debug:
    msg: "{{ pwstate.results }}"

- name: "Power Off VM"
  community.general.proxmox_kvm:
        proxmox_default_behavior: compatibility
        node: "{{ proxmox.node[px_var].name }}"
        api_user: "{{ proxmox.node[px_var].api_user }}"
        api_token_id: "{{ proxmox.node[px_var].api_token_id }}"
        api_token_secret: "{{ proxmox.node[px_var].api_token_secret }}"
        api_host: "{{ proxmox.node[px_var].api_host }}"
        name: "{{ item }}"
        state: stopped
#  when: pwstate.status is defined and pwstate.status == "running"
  run_once: True
  loop: "{{ server_hostname }}"

- name: Giving PVE some time to actually stop the VM...
  pause:
    minutes: 1
