---
- name: "Reboot VM"
  community.general.proxmox_kvm:
        proxmox_default_behavior: compatibility
        node: "{{ proxmox.node[px_var].name }}"
        api_user: "{{ proxmox.node[px_var].api_user }}"
        api_token_id: "{{ proxmox.node[px_var].api_token_id }}"
        api_token_secret: "{{ proxmox.node[px_var].api_token_secret }}"
        api_host: "{{ proxmox.node[px_var].api_host }}"
        name: "{{ item }}"
        timeout: 80
        state: restarted
  run_once: True
  loop: "{{ server_hostname }}"
  loop_control:
    pause: 5
