---

- name: "Set var filename"
  ansible.builtin.set_fact:
    output_file: "{{ pors_temp_dir }}/ansible.var"

- name: Ensure temp dir is there
  ansible.builtin.file:
    path: "{{ pors_temp_dir }}"
    state: directory

- name: Clean old var file
  ansible.builtin.file:
    path: "{{ pors_temp_dir }}/ansible_{{ varname }}.var"
    state: absent

- name: Get variable
  ansible.builtin.debug:
    var: "{{ item }}"
  loop: "{{ varname.split(',') if varname is defined and ',' in varname else [varname] }}"
  register: parsed_var

- name: Fill template
  ansible.builtin.template:
    src: getvar.yml.j2
    #src: get_var.yml.j2
    dest: "{{ pors_temp_dir }}/getvar.yml"
    mode: 0640

- include: "{{ pors_temp_dir }}/getvar.yml"

- name: Write variable
  ansible.builtin.lineinfile:
    path: "{{ pors_temp_dir }}/ansible_{{ varname }}.var"
    #path: "{{ output_file }}"
    line: >-
      {% if item.value is boolean %}{{ item.value}}{% else %}{{ item.value | join('|') }}{% endif %}
    create: yes
  loop: "{{ lookup('dict',parsed_var) }}"
  when:
    - item.key != "changed"
    - item.key != "failed"
