---
- name: Create a new application admin linux user (shell)
  hosts: "{{ target }}"
  remote_user: "{{ pors_ssh_user }}"
  become: yes
  become_user: root
  gather_facts: False

  vars:
    ansible_ssh_user: "{{ pors_ssh_user }}"

  tasks:

    - include_role:
        name: system_user
