- name: Deploy Journal Configs
  hosts: all
  become: yes
  become_user: root
  gather_facts: false

  vars:
    ansible_ssh_user: "{{ pors_ssh_user }}"


  pre_tasks:
    - include_vars: inventories/{{ target_env }}/group_vars/all/ansible

  roles:
    - system_journal
