---
- name: Manage a splunk user account (native auth)
  hosts: all
  remote_user: "{{ pors_ssh_user }}"
  become: yes
  become_user: "{{ splunk_install_user }}"
  gather_facts: false

  vars:
    ansible_ssh_user: "{{ pors_ssh_user }}"

  tasks:
    - name: "Create {{ user_name }} with role {{ user_role }}"
      shell: "{{ splunk_installation.splunk_home_path }}/bin/splunk add user {{ user_name }} -password '{{ user_password }}' -role {{ user_role }} -auth {{ vault_splunk_admin_user }}:{{ vault_splunk_admin_password }}"
      no_log: true
      when: create_user is defined

    - name: "Change {{ user_name }} , role {{ user_role }}"
      shell: "{{ splunk_installation.splunk_home_path }}/bin/splunk edit user {{ user_name }} -password '{{ user_password }}' -role {{ user_role }} -auth {{ vault_splunk_admin_user }}:{{ vault_splunk_admin_password }}"
      no_log: true
      when: edit_user is defined
