---
- hosts: all
  remote_user: "{{ pors_ssh_user }}"
  become: yes
  become_user: root
  gather_facts: false

  vars:
    ansible_ssh_user: "{{ pors_ssh_user }}"

  tasks:
    - include_role:
        name: system_optimize
        tasks_from: optimize_tuned
