---
- name: configure systemd journal daemon
  hosts: "*"
  remote_user: "{{ pors_ssh_user }}"
  become: yes
  become_user: root
  strategy: free
  gather_facts: false

  vars:
    ansible_ssh_user: "{{ pors_ssh_user }}"

  roles:
    - system_journal
