- name: System Upgrade
  hosts: "*"
  remote_user: "{{ pors_ssh_user }}"
  become: yes
  become_user: root
  strategy: free
  gather_facts: true

  vars:
    ansible_ssh_user: "{{ pors_ssh_user }}"

  tasks:

    - include_role:
        name: system_journal

    - include_role:
        name: system_upgrade

    - include_role:
        name: system_base
        tasks_from: set_unattended_upgrade.yml
      when: unattended_system_upgrade.enabled | d(False)
