- name: Install/Upgrade kernel
  hosts: "*:!pors_server"
  remote_user: "{{ pors_ssh_user }}"
  become: yes
  become_user: root
  strategy: free
  gather_facts: false

  vars:
    ansible_ssh_user: "{{ pors_ssh_user }}"

  roles:
    - system_kernel
