- name: Format new disk storage
  hosts: "{{ server_hostname }}"
  remote_user: "{{ pors_ssh_user }}"
  become: yes
  become_user: root
  gather_facts: False

  vars:
    # format defined disks within an instance
    format_disk: True
    ansible_ssh_user: "{{ pors_ssh_user }}"

  tasks:

    - include_role:
        name: system_disk
 
