---
# THIS GETS OVERWRITTEN EACH RUN FROM: roles/system/template/ DIRECTORY! 
#- name: set the var according to the users setting
#  set_fact: shouldinstall="{{ item.value.install }}"
#  when: item.key == "system"
#  with_dict: "{{ vars['app_variable'] }} |app_default"

#- name: Debug SYSTEM
#  debug: msg="items {{ item.value.install }}." verbosity=4
#  with_dict: "{{ vars['app_variable'] }}"

- name: Prepare local files (local/*.conf)
  connection: local
  become: no
  lineinfile:
        dest: "{{ item }}" 
        regexp: "^#+ ANSIBLE FILE-MANAGED - DO NOT TOUCH WITHOUT ANSIBLE.*"
        state: present
        line: "########## ANSIBLE FILE-MANAGED - DO NOT TOUCH WITHOUT ANSIBLE (last run initiated from: {{ ansible_conf.host }}) ##########\n"
        insertbefore: BOF
  with_fileglob: system/local/*.conf
#  when: shouldinstall == true


