---

- name: Add private key (SSH)
  ansible.builtin.copy:
    content: "{{ vault_ssh_privkey_splunk }}"
    force: True
    dest: "{{ splunk_installation.splunk_home_path }}/.ssh/id_rsa"
    mode: 0600
    owner: "{{ splunk_install_user }}"
    group: "{{ splunk_install_group }}"
  when: vault_ssh_privkey_splunk is defined
#  no_log: true

- name: "Add pub key (SSH)"
  ansible.builtin.copy:
    content: "{{ vault_ssh_pubkey_splunk }}"
    force: True
    dest: "{{ splunk_installation.splunk_home_path }}/.ssh/id_rsa.pub"
    mode: 0600
    owner: "{{ splunk_install_user }}"
    group: "{{ splunk_install_group }}"
  when: vault_ssh_pubkey_splunk is defined
