---

#- name: "Ensure home exists"
#  file:
#    path: "/home/{{ system_shared_service_account }}"
#    owner: "{{ system_shared_service_account }}"
#    mode: 0700
#    state: directory

- name: "Set/Update authorized keys for {{ system_shared_service_account }}"
  become: yes
  become_user: "{{ system_shared_service_account }}"
  ansible.posix.authorized_key:
    user: "{{ system_shared_service_account }}"
    state: present
    key: "{{ lookup('file', '{{ repo_base }}/common/ssh/authorized_keys_{{ system_shared_service_account }}') }}"
    exclusive: "{{ ssh_replace_authkeys | d(False) }}"
