---
# HINT: The "hosts" value here is a dynamic group name used in PORS

- name: Configure splunk masternode
  hosts: "{{ target }}"
  remote_user: "{{ pors_ssh_user }}"
  become: yes
  become_user: "{{ splunk_install_user }}"

  vars:
    splunk_restart: True

  tasks:

    - include_role:
        name: conf/user

    - include_role:
        name: system_sshid

    - include_role:
        name: conf/web

    - include_role:
        name: conf/outputs

    - include_role:
        name: conf/server

#    - include_role:
#        name: group/searchhead

    - include_role:
        name: common_tasks
        tasks_from: monitoring.yml

  # flush notify handlers to activate the splunk config
  post_tasks:
    - meta: flush_handlers

