---
- hosts: localhost 
  connection: local

  vars:
    tgzname: "{{ spltype }}-{{ globversion }}-{{ globhash }}-Linux-x86_64.tgz"

  tasks:
    - include_vars: ../../roles/common/defaults/main.yml
      when: spltype == "splunkforwarder"

    - include_vars: "{{ env_inventory_dir }}/group_vars/universal_forwarder/splunk_installation.yml"
      when: spltype == "splunkforwarder"

    - include_role:
        name: splunk_download
