---
- hosts: pors_server
  gather_facts: false

  roles:
    - splunk_sites

  tasks:
    - set_fact:
        parsed_groups: ["{{ target }}"]
      when: parsed_groups is not defined

    - name: Clean any previous tmp file
      file:
          path: "{{ expandfile }}"
          state: absent
      when: clean_tmp is defined and clean_tmp == "yes"

    - name: Delete any previous nogrp file
      file:
          path: "{{ expandfile }}.nogrp"
          state: absent
      when: clean_tmp is defined and clean_tmp == "yes"

#    - debug:
#        msg: "{{ parsed_groups }}"

    - name: "Write {{ expandfile }} file"
      ini_file:
        create: yes
        dest: "{{ expandfile }}"
        section: "{{ item }}"
        allow_no_value: yes
        option: "{{ groups[item] | join('\n') }}"
        state: present
      connection: local
      loop: "{{ parsed_groups }}"

    - name: "Write {{ expandfile }}.nogrp file"
      lineinfile:
        dest: "{{ expandfile }}.nogrp"
        line: "{{ groups[item] | join('\n') }}"
        state: present
        create: yes
      connection: local
      loop: "{{ parsed_groups }}"
