---
- hosts: pors_server
  connection: local
  gather_facts: false

  vars:
    custom_data_dir: "{{ data_dir }}/custom"

  pre_tasks:
    - name: Check if custom template exists
      stat:
        path: "{{ custom_data_dir }}/roles/common/templates/ae_deploy_apps_{{ target_env  }}.yml.j2"
      register: custom_templ

  tasks:

  - name: Find app roles (filter a subset)
    shell: "ls -1 {{ data_dir }}/custom/roles/apps | grep -E '(^{{ deploy_sub_apps }}$)'"
    register: app_roles
    when: deploy_type == "custom" and deploy_sub_apps is defined

  - name: Create ae_deploy_apps.yml (pors)
    template: src={{ base_install_dir }}/roles/common/templates/ae_deploy_apps_{{ target_env  }}.yml.j2
              dest={{ data_dir }}/inventories/{{ target_env }}/ae_deploy_apps.yml
              mode=0640
    when:
        - custom_templ.stat.exists != true
        - deploy_type == "custom"
        - deploy_sub_apps is defined
        - app_roles.stdout_lines is defined

  - name: Create ae_deploy_apps.yml (custom)
    template: src={{ custom_data_dir }}/roles/common/templates/ae_deploy_apps_{{ target_env  }}.yml.j2
              dest={{ data_dir }}/inventories/{{ target_env }}/ae_deploy_apps.yml
              mode=0640
    when:
        - custom_templ.stat.exists == true
        - deploy_type == "custom"
        - deploy_sub_apps is defined
        - app_roles.stdout_lines is defined

  - name: Find app roles (no filtering)
    shell: "ls -1 {{ data_dir }}/custom/roles/apps"
    register: app_roles
    when: deploy_type == "all"

  - name: Create ae_deploy_apps.yml (pors)
    template: src={{ base_install_dir }}/roles/common/templates/ae_deploy_apps_{{ target_env  }}.yml.j2
              dest={{ data_dir }}/inventories/{{ target_env }}/ae_deploy_apps.yml
              mode=0640
    when:
        - custom_templ.stat.exists != true
        - deploy_type == "all"
        - app_roles.stdout_lines is defined

  - name: Create ae_deploy_apps.yml (custom)
    template: src={{ custom_data_dir }}/roles/common/templates/ae_deploy_apps_{{ target_env  }}.yml.j2
              dest={{ data_dir }}/inventories/{{ target_env }}/ae_deploy_apps.yml
              mode=0640
    when:
        - custom_templ.stat.exists == true
        - deploy_type == "all"
        - app_roles.stdout_lines is defined


