---
- name: Upgrade System
  hosts: "*:!pors_server"
  remote_user: "{{ pors_ssh_user }}"
  become: yes
  become_user: root
  strategy: free
  gather_facts: False

  pre_tasks:
    - setup:
      when: system.upgrade_os is defined and system.upgrade_os == True

  roles:
    - { role: system_upgrade, when: system.upgrade_os is defined and system.upgrade_os == True }

- name: Upgrade Splunk
  hosts: "*:!pors_server"
  remote_user: "{{ pors_ssh_user }}"
  become: yes
  become_user: root
  strategy: free
  gather_facts: False 

  vars:
    splunk_upgrade: True
    splunk_type: "splunk"
    ansible_ssh_user: "{{ pors_ssh_user }}"

  pre_tasks:
    - include_vars: "{{ env_inventory_dir }}/group_vars/universal_forwarder/splunk_installation.yml"
      when: spltype is defined and spltype == "splunkforwarder"

    - set_fact:
        splunk_type: "{{ spltype }}"
      when: spltype is defined

    - setup:
      when: system.upgrade_os is undefined or system.upgrade_os == False

  roles:
    - splunk_info
    - install

- name: Upgrade Shelper
  include: ../shelper/ae_install_shelper.yml
  when: shelper_installation.enabled
