---

- name: Upgrade Splunk
  hosts: "*:!pors_server"
  remote_user: "{{ pors_ssh_user }}"
  become: yes
  become_user: root
  strategy: free
  gather_facts: False 

  vars:
    splunk_upgrade: True
    splunk_type: "splunk"
    ansible_ssh_user: "{{ pors_ssh_user }}"

  pre_tasks:
    - include_vars: "{{ env_inventory_dir }}/group_vars/universal_forwarder/splunk_installation.yml"
      when: spltype is defined and spltype == "splunkforwarder"

    - set_fact:
        splunk_type: "{{ spltype }}"
      when: spltype is defined

    - name: "Collecting system information"
      setup:

  tasks:

    - include_role:
        name: splunk_info

    - include_role:
        name: install

- ansible.builtin.import_playbook: ../shelper/ae_install_shelper.yml
- ansible.builtin.import_playbook: ../system/ae_system_upgrade.yml
