---

- ansible.builtin.import_playbook: ../shelper/ae_install_shelper.yml

- name: Backup Splunk
  hosts: "*:!pors_server"
  remote_user: "{{ pors_ssh_user }}"
  become: yes
  become_user: root
  gather_facts: true
  strategy: free

  vars:
    splunk_upgrade: False

  tasks:

    - include_role:
        name: install
        tasks_from: backup_splunk.yml

