---
# HINT: The "hosts" value here is a dynamic group name used in PORS

- name: "Configure a splunk shcmember"
  hosts: "{{ target }}"
  remote_user: "{{ pors_ssh_user }}"
  become: yes
  become_user: "{{ splunk_install_user }}"

  vars:
    splunk_restart: true

  tasks:

    - include_role:
        name: common
        public: yes

    - include_role:
        name: conf/server
        tasks_from: shclustering/detention.yml
      vars:
          shc_detention_state: true

    - include_role:
        name: conf/user

    - include_role:
        name: conf/ldap

    - include_role:
        name: system_sshid

    - include_role:
        name: conf/web

    - include_role:
        name: conf/outputs

    - include_role:
        name: conf/server

    - include_role:
        name: group/shcmember

- name: "Deploy keys (peernode)"
  hosts: "{{ target }}"
  remote_user: "{{ pors_ssh_user }}"
  become: yes
  become_user: "{{ splunk_install_user }}"

  vars:
    parsed_groups: "peernode"
    splunk_restart: true

  tasks:
    - include_role:
        name: group/searchhead

  post_tasks:

    - include_role:
        name: common
        public: yes

    - include_role:
        name: conf/server
        tasks_from: shclustering/detention.yml
      vars:
          shc_detention_state: false

    # flush notify handlers to force-activate the splunk config
    - meta: flush_handlers

