---

- name: "Renew splunk SSL certificates"
  hosts: all
  remote_user: "{{ pors_ssh_user }}"
  become: yes
  become_user: "{{ splunk_install_user }}"

  vars:
    splunk_restart: true

  tasks:
    - include_role:
        name: splunk_default_certs
      when: splunk_upgrade_manage_default_certs

  handlers:
    - include: ../../roles/common/handlers/splunkd.yml

  # flush notify handlers to activate the splunk config
#  post_tasks:
#    - meta: flush_handlers

