- name: Configure cribl logstream
  hosts: "{{ target }}"
  remote_user: "{{ cribl_ssh_user }}"
  become: yes
  become_user: root
  gather_facts: true
  strategy: free

  vars:
    logstream_upgrade: False
    skip_ssh_splunk_privkey: True
    skip_ssh_splunk_authkey: True

  tasks:

     - block:

        - include_role:
            name: logstream_configure

        - include_role:
            name: system_sshid

       rescue:

          - fail:
              msg: |
                ERROR OCCURED:
                
                {{ ansible_failed_result.msg | replace('"','') |replace("'","") | regex_replace('[}{]','') }}
                
                See above for details.
