---
- name: splunk start
  shell: "{{ splunk_installation.splunk_home_path }}/bin/splunk start --accept-license --answer-yes"
  when: (splunk_start is defined and splunk_start) or ( splunk_action is defined and splunk_action == "start")
  register: action_result

- name: splunk stop
  shell: "{{ splunk_installation.splunk_home_path }}/bin/splunk stop"
  when: (splunk_stop is defined and splunk_stop) or ( splunk_action is defined and splunk_action == "stop")
  register: action_result

- name: splunk restart
  shell: "{{ splunk_installation.splunk_home_path }}/bin/splunk restart --accept-license --answer-yes"
  when: ((splunk_restart is defined and splunk_restart) or ( splunk_action is defined and splunk_action == "restart"))
  register: action_result

- name: splunk restartweb
  become: true
  become_user: "{{ splunk_install_user }}"
  shell: "{{ splunk_installation.splunk_home_path }}/bin/splunk restart splunkweb --accept-license --answer-yes -auth '{{ vault_splunk_ae_user }}:{{ vault_splunk_ae_password }}'"
  when: ((splunk_restartweb is defined and splunk_restartweb) or ( splunk_action is defined and splunk_action == "restartweb"))
  no_log: true
  register: action_result

- name: splunk custom
  become: true
  become_user: "{{ splunk_install_user }}"
  shell: "{{ splunk_installation.splunk_home_path }}/bin/splunk {{ splunk_cmdparams }} --accept-license --answer-yes -auth '{{ vault_splunk_ae_user }}:{{ vault_splunk_ae_password }}'"
  when: splunk_action is defined and splunk_action == "custom" and splunk_cmdparams is defined
  no_log: true
  register: action_result
