---

- name: "Add splunk user(s)"
  block:

    - name: "Set vars"
      ansible.builtin.set_fact: 
        splunk_username: "{{ splacc.usr }}"
        splunk_password: "{{ splacc.pwd }}"
        splunk_user_role: "{{ splacc.role }}"
      no_log: true

    - include_role:
        name: install
        tasks_from: splunk_start.yml

    - include_role:
        name: install
        tasks_from: add_spl_ae_user.yml


