---
- name: "Open splunkd port on firewalld"
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled 
  when:
    - splunk_installation.firewalld_open_port is defined
    - splunk_installation.firewalld_disabled is not defined
  with_items: splunk_installation.firewalld_open_port | default()

- name: "Disable firewalld completely"
  ansible.builtin.systemd_service: 
    name: firewalld
    enabled: no
    state: stopped
    masked: yes
  when: splunk_installation.firewalld_disable is defined
