---
- include: sys_check.yml

- include: firewalld.yml

- include: optimize_tuned.yml
  when: 
    - splunk_optimize.tuned is defined
    - splunk_optimize.tuned == True

- include: optimize_selinux.yml
  when: 
    - system.selinux is defined

# - include: set_perms.yml
