---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure NTP-related packages are installed.
  package:
    name: ntp
    state: present
  when: ansible_os_family == 'RedHat' and ansible_distribution_version.split('.')[0] =< '6'

- name: Ensure NTP-related packages are installed.
  package:
    name: chrony
    state: present
  when: ansible_os_family == 'RedHat' and ansible_distribution_version.split('.')[0] >= '7'

- name: Ensure tzdata package is installed (Linux).
  package:
    name: "{{ ntp_tzdata_package }}"
    state: present
  when: ansible_system == "Linux"

- include_tasks: clock-rhel-7.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_version.split('.')[0] == '7'

- name: Set timezone
  timezone:
    name: "{{ ntp_timezone }}"

- name: Ensure NTP is running and enabled as configured.
  service:
    name: "{{ ntp_daemon }}"
    state: started
    enabled: true
  when: ntp_enabled | bool

- name: Ensure NTP is stopped and disabled as configured.
  service:
    name: "{{ ntp_daemon }}"
    state: stopped
    enabled: false
  when: not (ntp_enabled | bool)

- name: Generate ntp.conf file
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify: restart ntp
  when: ntp_manage_config | bool
