---

- name: "Templatizing {{ dnsmasq_configure_conf_path }}"
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: '{{ dnsmasq_configure_conf_path }}'
    mode: '644'
  register: dnsmasq_conf

- block:

  - name: "Use dnsmasq in NetworkManager"
    community.general.ini_file:
      path: /etc/NetworkManager/conf.d/00-use-dnsmasq.conf
      section: main
      option: dns
      value: dnsmasq
      no_extra_spaces: true
      create: true
    register: dnsmasq_nm_setup

  - name: "Include dnsmasq config in NetworkManager"
    community.general.ini_file:
      path: /etc/NetworkManager/dnsmasq.d/dnsmasq.conf
      option: "conf-file"
      value: "{{ dnsmasq_configure_conf_path }}"
      no_extra_spaces: true
      create: true
    register: dnsmasq_nm_conf

  when: dnsmasq_configure_networkmanager
