---

- include_role:
    name: ssh/check

- include: set_touch_dir.yml
- include: check_sudo.yml

- include: gather_facts.yml
  tags: task_gather_facts
  when:
    - ssh_avail is defined

#- include: packages.yml
