---

- name: reboot remote system
  reboot:
    msg: "reboot initiated by PORS"
  register: rebootsys

- name: verify system reboot
  fail:
    msg: "ERROR: Failed to reboot the remote system or it has taken too long to boot up again"
  when: rebootsys.rebooted != True
