---
#- name: Clean previous backup
#  become: yes
#  become_user: root
#  ansible.builtin.shell: "rm -rf {{ splunk_installation.backup_target_dir }}/splunk/*"

- name: "Ensure backup path exists"
  ansible.builtin.file:
    path: "{{ splunk_installation.backup_target_dir }}"
    state: directory
    mode: 0700

- name: "Starting backup..."
  ansible.builtin.debug:
    msg: "backing up: {{ splunk_installation.backup_path }} now.."

- name: "Set KVstore backup file name"
  ansible.builtin.set_fact:
    backup_filename_kvstore: "backup_{{ inventory_hostname_short }}_{{ now(utc=false,fmt='%Y-%m-%d_%H-%M') }}_kvstore"
 
- name: "KVstore backup"
  block:

    - name: "Wait for KV store to be ready for backup"
      ansible.builtin.uri:
        use_proxy: false
        body_format: form-urlencoded
        body:
          output_mode: json
        force_basic_auth: true
        method: GET
        return_content: true
        status_code: [200]
        url_username: "{{ vault_splunk_ae_user }}"
        url_password: "{{ vault_splunk_ae_password }}"
        url: https://localhost:{{ splunk_install_management_port }}/services/kvstore/status
        validate_certs: false
      check_mode: false
      register: _splunk_backup_kvstore_status
      until: >-
        _splunk_backup_kvstore_status.status == 200 and
        _splunk_backup_kvstore_status.json.entry[0].content.current.backupRestoreStatus == "Ready" and
        _splunk_backup_kvstore_status.json.entry[0].content.current.status == "ready"
      delay: "{{ splunk_installation.backup_kvstore_delay }}"
      retries: "{{ splunk_installation.backup_kvstore_retries }}"

    - name: "Backup KV store"
      ansible.builtin.uri:
        use_proxy: false
        body_format: form-urlencoded
        body:
          pointInTime: "{% if (shc_site | default('undefined')) + '_shcmember' in group_names %}false{% else %}true{% endif %}"
          output_mode: json
          archiveName: "{{ backup_filename_kvstore }}"
        force_basic_auth: true
        method: POST
        return_content: false
        status_code: [200]
        url_username: "{{ vault_splunk_ae_user }}"
        url_password: "{{ vault_splunk_ae_password }}"
        url: https://localhost:{{ splunk_install_management_port }}/services/kvstore/backup/create
        validate_certs: false
      when:
        - _splunk_backup_kvstore_status.json.entry[0].content.current.replicationStatus == "KV store captain"
      changed_when: _splunk_backup_kvstore_result.status == 200
      any_errors_fatal: true
      register: _splunk_backup_kvstore_result

    - name: "Wait for finishing KV store backup"
      ansible.builtin.uri:
        use_proxy: false
        body_format: form-urlencoded
        body:
          output_mode: json
        force_basic_auth: true
        method: GET
        return_content: true
        status_code: [200]
        url_username: "{{ vault_splunk_ae_user }}"
        url_password: "{{ vault_splunk_ae_password }}"
        url: https://localhost:{{ splunk_install_management_port }}/services/kvstore/status
        validate_certs: false
      check_mode: false
      register: _splunk_backup_kvstore_status
      until: >-
        _splunk_backup_kvstore_status.status == 200 and
        _splunk_backup_kvstore_status.json.entry[0].content.current.backupRestoreStatus == "Ready" and
        _splunk_backup_kvstore_status.json.entry[0].content.current.status == "ready"
      delay: "{{ splunk_installation.backup_kvstore_delay }}"
      retries: "{{ splunk_installation.backup_kvstore_retries }}"

    - name: "Upload KVstore backup to {{ splunk_installation.backup_upload_rsync_server }}"
      ansible.posix.synchronize:
        mode: push
        src: "{{ splunk_installation.splunk_home_path }}/var/lib/splunk/kvstorebackup/{{ backup_filename_kvstore }}.tar.gz"
        dest: "rsync://{{ vault_splunk_rsync_user }}@{{ splunk_installation.backup_upload_rsync_server }}/{{ splunk_installation.backup_upload_rsync_module }}"
        rsync_timeout: "{{ splunk_installation.backup_upload_timeout }}"
      environment:
        RSYNC_PASSWORD: "{{ vault_splunk_rsync_password }}"
      delegate_to: "{{ inventory_hostname }}"
      when: splunk_installation.backup_upload

  when: splunk_installation.backup_kvstore

- name: "Set backup file name"
  ansible.builtin.set_fact:
    backup_filename: "backup_{{ inventory_hostname_short }}_{{ now(utc=false,fmt='%Y-%m-%d_%H-%M') }}.tar.gz"
  
# do not use copy due to its limitations
# copy facility does not scale to lots of files
- name: "Backup specified path(s)"
#  become: yes
#  become_user: root
  community.general.archive:
    path: "{{ splunk_installation.backup_path }}"
    dest: "{{ splunk_installation.backup_target_dir }}/{{ backup_filename }}"
    exclusion_patterns: "{{ splunk_installation.backup_exclusion_patterns }}"
    format: gz

- name: "Upload backup to {{ splunk_installation.backup_upload_rsync_server }}"
#  become: yes
#  become_user: root
  ansible.posix.synchronize:
    mode: push
    src: "{{ splunk_installation.backup_target_dir }}/{{ backup_filename }}"
    dest: "rsync://{{ vault_splunk_rsync_user }}@{{ splunk_installation.backup_upload_rsync_server }}/{{ splunk_installation.backup_upload_rsync_module }}"
    rsync_timeout: "{{ splunk_installation.backup_upload_timeout }}"
  environment:
    RSYNC_PASSWORD: "{{ vault_splunk_rsync_password }}"
  delegate_to: "{{ inventory_hostname }}"
  when: splunk_installation.backup_upload

- name: "Cleanup"
  ansible.builtin.shell: |
    find {{ splunk_installation.backup_target_dir }} -type f -name '*.tar.gz' -delete
    find {{ splunk_installation.splunk_home_path }}/var/lib/splunk/kvstorebackup -type f -name '*.tar.gz' -delete

