---

- name: Check if passwd file exists
  stat: path={{ splunk_installation.splunk_home_path }}/etc/passwd
  register: has_passwd_file

- name: Change default password (pre v8)
  command: "{{ splunk_installation.splunk_home_path }}/bin/splunk edit user admin -password '{{ splunk_auth.admin_password }}' -auth admin:changeme --accept-license"
  become: yes
  become_user: "{{ splunk_install_user }}"
  when: 
    - has_passwd_file.stat.exists == true
    - splunk_upgrade == False

- name: Add admin account (passwd does not exist)
  lineinfile: 
    dest: "{{ splunk_installation.splunk_home_path }}/etc/system/local/user-seed.conf"
    create: yes
    line: "[user_info]\nUSERNAME={{ vault_splunk_admin_user }}\n{%if vault_splunk_admin_password_hashed is defined %}HASHED_PASSWORD={{ vault_splunk_admin_password_hashed }}{%elif vault_splunk_admin_password is defined %}PASSWORD={{ vault_splunk_admin_password }}{% endif %}"
  when: 
    - has_passwd_file.stat.exists == false
    - splunk_upgrade == False
    - (vault_splunk_admin_password is defined or vault_splunk_admin_password_hashed is defined)
