---

- name: "Check init/systemd conf files"
  block:

    - stat:
        path: /etc/init.d/splunk
      register: splunkinitfile

    - stat:
        path: "/etc/systemd/system/{{ splunk_systemd_unit_name }}.service"
      register: splunksysdfile

- name: "Remove legacy initd script"
  block:

    - name: "Stop splunk's initd service"
      ansible.builtin.systemd_service:
        name: splunk
        state: stopped

    # file attr doesnt work and is available in ansible version >= v2.3 only
    - name: Remove protection from splunk init.d script
      shell: chattr -i /etc/init.d/splunk
      when: 
        - splunkinitfile is defined and splunkinitfile.stat.exists
        - run_in_docker.rc == 1

    - name: Remove an existing init.d script
      file: path=/etc/init.d/splunk
            state=absent

    - name: "Reload systemd conf"
      ansible.builtin.systemd_service:
        daemon_reload: true
      when: run_in_docker.rc == 1

  when: splunkinitfile is defined and splunkinitfile.stat.exists

- name: "Show splunk version"
  debug:
    msg: "splunk version is: >{{ splunkversionnum }}<"
    
- name: "Prep splunk-launch.conf"
  copy:
    remote_src: true
    src: "{{ splunk_installation.splunk_home_path }}/etc/splunk-launch.conf.default"
    dest: "{{ splunk_installation.splunk_home_path }}/etc/splunk-launch.conf"
    owner: "{{ splunk_install_user }}"
    group: "{{ splunk_install_user }}"

- name: "Unprotect splunk's systemd service"
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ splunk_systemd_unit_name }}.service"
    attr: -i
  when: splunksysdfile is defined and splunksysdfile.stat.exists

- name: "Disable boot start"
  shell: |
    {{ splunk_installation.splunk_home_path }}/bin/splunk disable boot-start
    {{ splunk_installation.splunk_home_path }}/bin/splunk disable boot-start --no-prompt -systemd-managed 1 -systemd-unit-file-name {{ splunk_systemd_unit_name }}
  when: splunk_upgrade

#- block:
#
#    - name: "Backup previous polkit rules"
#      copy:
#        remote_src: True
#        src: "/etc/polkit-1/rules.d/10-Splunkd.rules"
#        dest: "/etc/polkit-1/rules.d/10-Splunkd.rules.upgr-{{ splunkversionnum }}"
#
#    - name: "Remove previous polkit rules"
#      file:
#        path: "/etc/polkit-1/rules.d/10-Splunkd.rules"
#        state: absent
#
#  when: splunk_upgrade

- name: "Enable Splunk boot-start (systemd)"
  shell: |
    {{ splunk_installation.splunk_home_path }}/bin/splunk enable boot-start -user {{ splunk_install_user }} --answer-yes --accept-license --no-prompt -systemd-managed 1 -systemd-unit-file-name {{ splunk_systemd_unit_name }} -create-polkit-rules 1
  register: enableinit
  failed_when: enableinit.rc != 0 and enableinit.rc != 8

- name: "Identify systemd version"
  ansible.builtin.shell: systemctl --version | head -1 | awk '{ print $2}'
  register: systemd_version

- name: "Replace legacy systemd options"
  block:

    - name: "Remove"
      community.general.ini_file:
        path: "/etc/systemd/system/{{ splunk_systemd_unit_name }}.service"
        section: Service
        option: "{{ item }}"
        state: absent
      loop:
        - CPUShares
        - MemoryLimit

    - name: "Calc max mem (incl 4G buffer)"
      ansible.builtin.set_fact:
        sysd_maxmem: >-
          {% if ansible_memtotal_mb < 4096 %}{{ ansible_memtotal_mb}}{% else %}{{ ansible_memtotal_mb - 4096 }}{% endif %}

    - name: "Add"
      community.general.ini_file:
        path: "/etc/systemd/system/{{ splunk_systemd_unit_name }}.service"
        section: Service
        option: "{{ item.o }}"
        value: "{{ item.v }}"
        state: present
        no_extra_spaces: true
      loop:
        - { o: 'CPUWeight', v: 1024 }
        - { o: 'MemoryMax', v: "{{ sysd_maxmem }}M" }

  when: systemd_version.stdout | int >= 252

- name: "Protect splunk's systemd service"
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ splunk_systemd_unit_name }}.service"
    attr: +i

- name: "Enable splunk's systemd service"
  ansible.builtin.systemd_service:
    enabled: yes
    daemon_reload: true
    name: "{{ splunk_systemd_unit_name }}"
  when: 
    - "run_in_docker.rc == 1"
