---
- name: Install Splunk package from rpm
  yum: name="{{ splunk_installation.remote_package_temp_path }}/{{ splunk_installation.package_file }}" 
       state=present
  when: splunk_installation.package_format == "rpm"

- name: Install Splunk package from tgz (shell mod)
  shell: "tar xzf {{ splunk_installation.remote_package_temp_path }}/{{ splunk_installation.package_file }}"
  args:
    chdir: /opt
  when:  splunk_installation.package_format == "tgz"

- name: Remove temporary Splunk package
  command: rm "{{ splunk_installation.remote_package_temp_path }}/{{ splunk_installation.package_file }}"
  when: splunk_installation.delete_package_after_install != false

- include_tasks: set_perms.yml
