---
- include: sys_check.yml

- include: package.yml

- include: prepare_splunk.yml
  when: splunk_upgrade == False

- include: operation_mode.yml

- include: transfer_pkg.yml

- include: splunk_stop.yml
  # this condition will fail on half-installed splunk re-installs
  when: splunk_upgrade == True

- include: backup_splunk.yml
  when: 
    - splunk_installation.backup is defined and splunk_installation.backup == true
    - splunk_upgrade == True

- include: install_splunk.yml

- name: "CUSTOM: post-install tasks (if defined)"
  include_role:
    name: custom_post_install_splunk
  when:
    - hook_post_install_splunk is defined and hook_post_install_splunk == True
    - splunk_upgrade == False

- include: ../../splunk_info/tasks/installed_version.yml

- include: set_splunk_secret.yml
  when: splunk_upgrade == False

- include: enable_boot_start_splunk.yml

- include: add_authorized_key.yml
  when: splunk_upgrade == False

- include: firewalld.yml
  when:
    - splunk_upgrade == False
    - splunk_installation.firewalld_disable != False
    - "'firewalld' in ansible_facts.packages"

- include: splunk_startstop.yml
  when: splunk_upgrade == False

- include: change_default_password.yml
  when: splunk_upgrade == False

- include: fetch_distserverkeys.yml
  when:
    - splunk_upgrade == False
    - splunk_type != "splunkforwarder"

- include: ../../system_optimize/tasks/optimize_tuned.yml
  when: 
    - splunk_optimize.tuned is defined
    - splunk_optimize.tuned == True
    - splunk_type != "splunkforwarder"

- include: optimize_initd.yml
  when: 
    - splunk_optimize.initd is defined
    - splunk_optimize.initd == True
#    - splunkversionnum < 72
    
- include: ../../system_optimize/tasks/optimize_selinux.yml

- include: set_perms.yml

- include_tasks: optimize_ulimit.yml

- include: splunk_start.yml
#  when:
#    - splunk_upgrade == False
#    - splpeernode.stdout != "slave" 

- include: add_spl_ae_user.yml 
  when: vault_splunk_ae_user is defined and splunk_upgrade == False

- include: post_actions.yml
  when: splunk_upgrade == False

- include: sudoperms.yml
  when: install_splunk_sudoperms is defined and install_splunk_sudoperms == true
