---
- name: Check if we are running in a cluster (Indexer)
  ansible.builtin.shell: |
    RET=$({{ splunk_installation.splunk_home_path }}/bin/splunk btool server list clustering --debug 2> /dev/null | grep -v "/etc/system/default" | grep -c -E 'mode.*=.*(peer|slave)')
    if [ "$RET" -ge 1 ];then echo "peer"; fi
  register: splpeernode

- name: Check if we are running in a cluster (SearchHead)
  ansible.builtin.shell: |
    RET=$({{ splunk_installation.splunk_home_path }}/bin/splunk btool server list shclustering --debug 2> /dev/null | grep -v "/etc/system/default" | grep 'disabled' | grep -c -E "0|[Ff]alse")
    if [ "$RET" -ge 1 ];then echo "member"; fi
  register: splshcmember
