---
- name: Check if we are running in a cluster (Indexer)
  shell: "{{ splunk_installation.splunk_home_path }}/bin/splunk btool server list clustering | egrep '^mode' |tr -d ' ' |cut -d '=' -f 2"
  register: splpeernode

- name: Check if we are running in a cluster (SearchHead)
  shell: "{{ splunk_installation.splunk_home_path }}/bin/splunk btool server list shclustering | egrep '^mode' |tr -d ' ' |cut -d '=' -f 2"
  register: splshcmember
