---

# FIXIT? when splunk 7.2.x has NOT been set with "enable boot-start --systemd-managed 0"
# possible way: check for Systemd file existence instead of splunk version
- name: Stop splunk by systemd
  service:
    name: Splunkd
    state: stopped
  when: splunksystemdfile is defined and splunksystemdfile.stat.exists

- name: Stop Splunk (non-systemd only)
  service: name=splunk
           state=stopped
  ignore_errors: yes
  when: splunksystemdfile is not defined or splunksystemdfile.stat.exists == false

- name: Stop Splunk by binary
  shell: "{{ splunk_installation.splunk_home_path }}/bin/splunk stop"
  async: 1800
  poll: 0
  register: splunk_stopped_by_bin

- name: ... is Splunk by bin stopped (non-indexers only)?
  async_status: jid={{ splunk_stopped_by_bin.ansible_job_id }}
  register: splunk_bin_stopped_result
  until: splunk_bin_stopped_result.finished
  retries: 360

# ensure splunk is REALLY not running anymore! Do not rely on init, systemd etc!!
- name: Re-Check Splunk Status
  shell: "ps aux | grep splunkd | grep -Ev '(ssh|grep|tail|less|vim|vi|patrol|ansible)'"
  async: 1800
  poll: 0
  register: splunk_laststate
  failed_when: splunk_laststate.rc == 0
  ignore_errors: true

- name: ... all Splunk processes REALLY stopped?
  async_status: jid={{ splunk_laststate.ansible_job_id }}
  register: splunk_allprocs_result
  until: splunk_allprocs_result.finished
  retries: 100
  delay: 20
