---
- name: Import splunk checks
  import_tasks: splunk_checks.yml

# check for existence of splunk bin file
- stat: path="{{ splunk_installation.splunk_home_path }}/bin/splunk"
  register: splunkbin
  failed_when: splunkbin.stat.exists != True

- name: systemctl reload
  shell: systemctl daemon-reload
  ignore_errors: yes
 
- name: Start Splunk by service
  import_tasks: splunk_service_start.yml 
 
# ensure splunk is REALLY running ! Do not rely on init, systemd etc!!
- name: Re-Check Splunk Status
  shell: "sleep 10s && ps aux |grep -vE '(ssh|grep|tail|less|vim|vi|patrol|ansible)' |grep 'splunkd '"
  register: splunk_laststate
  failed_when: splunk_laststate.rc != 0

