---

- block:

    - name: "Login to Cluster Leader"
      shell: |
        {{ splunk_installation.splunk_home_path }}/bin/splunk login -auth '{{ vault_splunk_ae_user }}:{{ vault_splunk_ae_password }}'
      register: splauth
      retries: 15
      delay: 20
      until: splauth.rc == 0
      delegate_to: "{{ groups['masternode'][0] }}"

    - name: "Check & enable rolling upgrade mode"
      shell: |
        INITDONE=$({{ splunk_installation.splunk_home_path }}/bin/splunk show cluster-status --verbose | grep -ci 'rolling upgrade is in progress')
        if [ "$INITDONE" -eq 0 ];then
          {{ splunk_installation.splunk_home_path }}/bin/splunk upgrade-init cluster-peers \
            || {{ splunk_installation.splunk_home_path }}/bin/splunk show cluster-status --verbose | head -n 50
        else
          echo "skipped already initialized rolling-restart"
        fi
      delegate_to: "{{ groups['masternode'][0] }}"

    - name: "Hint: manual splunk upgrade-finalize cluster-peers required!"
      debug:
        msg: |

            You have to finalize manually at the very end as PORS is not aware of the overall state.
            Execute this on the Manager Node once fully completed:

            $> splunk upgrade-finalize cluster-peers

  when: idxc_rolling_upgrade

# check if this is an indexer peer and take offline if (will fail after 30 min >retries< wait time)
- name: Take Splunk offline (indexer cluster peer)
  shell: "{{ splunk_installation.splunk_home_path }}/bin/splunk offline -auth '{{ vault_splunk_ae_user }}:{{ vault_splunk_ae_password }}'"
  become: yes
  become_user: "{{ splunk_install_user }}"
  async: 1800
  poll: 0
  register: splunk_ix_is_stopped
  ignore_errors: yes
  no_log: true
  when: 
     - splunk_state.rc == 0
     - splpeernode.stdout == "peer"

# to catch the job id we need to become the same user than the offline cmd uses
- name: ... is Splunk offline (indexer cluster peer)?
  async_status: jid={{ splunk_ix_is_stopped.ansible_job_id }}
  register: splunk_ix_is_stopped_result
  until: splunk_ix_is_stopped_result.finished
  become: yes
  become_user: "{{ splunk_install_user }}"
  retries: 360
  ignore_errors: yes
  when:
     - splunk_state.rc == 0
     - splunk_ix_is_stopped is defined
     - splpeernode.stdout == "peer"

