---

- name: "Block: SHC"
  become: yes
  become_user: "{{ splunk_install_user }}"
  block:

    # disable detention mode
    # if the lock cannot be obtained we need to wait until it is free again.
    # "Conf is currently being modified by process xxx. Failed to obtain config lock.  Exiting."
    - name: "Disable detention mode (SH cluster)"
      ansible.builtin.shell: |
        CNT=0
        while [ "$CNT" -lt 5 ];do
          CNT=$((CNT +1))
          {{ splunk_installation.splunk_home_path }}/bin/splunk edit shcluster-config -manual_detention off && break
          ERR=$?
          sleep 20
        done
        exit $ERR

    - name: "Hint: manual splunk upgrade-finalize shcluster-members required!"
      debug:
        msg: |

            You have to finalize manually at the very end as PORS is not aware of the overall state.
            Execute this on any SHC member once completed:

            $> splunk upgrade-finalize shcluster-members


